First_Number = int(input("Enter First Number : "))
Second_Number = int(input("Enter Second Number : "))
print("=-=-=-=-=","Basic Arithmetic Operations","=-=-=-=-=\n")
print("            ","Addition =",First_Number+Second_Number)
print("            ","Subration =",First_Number-Second_Number)
print("            ","Multiplication =",First_Number*Second_Number)
print("            ","Division =",First_Number/Second_Number,)
print("            ","Modulus =",First_Number%Second_Number,"\n")
print("=-"*23)