message = "This is Pakistan. The Most Beautiful Country of the world"
# print("capitalize :", message.capitalize())
# print("casefold :", message.casefold())
# print("center :", message.center(10," "))
# print("count :", message.count("T"))
# print("encode :", message.encode())
# print("endswith :", message.endswith("world"))
# print("expandtabs :", "Hello\tWorld".expandtabs(4))
# print("find :", message.find("Pakistan"))
# print("format :", "My name is {}".format("Asad"))
# print("format_map :", "Name: {name}".format_map({"name": "Asad"}))
# print("index :", message.index("Pakistan"))
# print("isalnum :", "ABC123".isalnum())
# print("isalpha :", "ABC".isalpha())
# print("isascii :", message.isascii())
# print("isdecimal :", "123".isdecimal())
# print("isdigit :", "123".isdigit())
# print("isidentifier :", "my_var".isidentifier())
# print("islower :", "hello".islower())
# print("isnumeric :", "123".isnumeric())
# print("isprintable :", message.isprintable())
# print("isspace :", "   ".isspace())
# print("istitle :", message.istitle())
# print("isupper :", "HELLO".isupper())
# print("join :", "-".join(["A", "B", "C"]))
# print("ljust :", "Hi".ljust(10, "-"))
# print("lower :", message.lower())
# print("lstrip :", "   hello".lstrip())
# print("partition :", message.partition("Pakistan"))
# print("replace :", message.replace("Pakistan", "India"))
# print("rfind :", message.rfind("is"))
# print("rindex :", message.rindex("is"))
# print("rjust :", "Hi".rjust(10, "-"))
# print("rpartition :", message.rpartition("is"))
# print("rsplit :", message.rsplit(" ", 2))
# print("rstrip :", "hello   ".rstrip())
# print("split :", message.split(" "))
# print("splitlines :", "Hello\nWorld".splitlines())
# print("startswith :", message.startswith("This"))
# print("strip :", "   hello   ".strip())
# print("swapcase :", message.swapcase())
# print("title :", message.title())

# table = str.maketrans("P", "B")
# print("translate :", message.translate(table))

# print("upper :", message.upper())
# print("zfill :", "42".zfill(5))