# print("==="*8)
# Number = int(input("Enter a Number : "))
# print("====","Table of",Number,"is","====" )
# print("=   ",Number,"*",1," =",Number*1,"    =")
# print("=   ",Number,"*",2," =",Number*2,"   =")
# print("=   ",Number,"*",3," =",Number*3,"   =")
# print("=   ",Number,"*",4," =",Number*4,"   =")
# print("=   ",Number,"*",5," =",Number*5,"   =")
# print("=   ",Number,"*",6," =",Number*6,"   =")
# print("=   ",Number,"*",7," =",Number*7,"   =")
# print("=   ",Number,"*",8," =",Number*8,"   =")
# print("=   ",Number,"*",9," =",Number*9,"   =")
# print("=   ",Number,"*",10,"=",Number*10,"   =")
# print("=="*11)